name: Cypress MongoDb Example

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'

      - name: Start MongoDb
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Execute the Tests
        run: yarn test
