name: Cypress MongoDb Example

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node18.12.0-chrome106-ff106
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Start MongoDb
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          browser: chrome
          headed: false
