name: Cypress MongoDb Example

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          check-latest: true
          cache: 'npm'

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.29.7/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Start MongoDb
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Install Dependencies
        run: npm ci

      - name: Execute the Tests
        run: npm run test
